export const DEVICE_CONSTANTS = {
  // Connection
  RECONNECT_ATTEMPTS: 5,
  RECONNECT_DELAY_MS: 1000,
  HEARTBEAT_INTERVAL_MS: 30000,
  CONNECTION_TIMEOUT_MS: 10000,

  // Wake word
  DEFAULT_WAKE_WORD: 'hey bot',
  WAKE_WORD_SENSITIVITY: 0.5,

  // Audio
  DEFAULT_VOLUME: 70,
  MAX_VOLUME: 100,
  MIN_VOLUME: 0,

  // ESP32 specific
  ESP32_BUFFER_SIZE: 1024,
  ESP32_SAMPLE_RATE: 16000,
} as const;
